# Set the maximum line length to 79.
line-length = 79

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[format]
docstring-code-format = true
docstring-code-line-length = 72

