name: Release on New Tag

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile  --windowed src/main.py

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist\main.exe
